In [1]:
num_list = [5,8,2,4,7,9]
def sum(arr):
    sum = 0
    for num in arr:
        sum += num
    return sum
sum(num_list)

35

In [4]:
num_list = [4,3,5,6,2]
def mul_func(arr):
    product = 1
    for num in arr:
        product *= num
    return product
mul_func(num_list)

720

In [45]:
import numpy as np

arr = np.array([
    [5,5,8,8,9,8],
    [7,7,5,3,5,7],
    [8,7,8,4,2,6],
    [9,9,7,3,1,4]])

print('a) Sort the flattened array')
print(np.sort(arr, axis = None))
print('\nb) Sort the second column')
print(np.sort(arr[:,1]))
print('\nc) Sort the third row')
print(np.sort(arr[2,:]))
print('\nd) Extract the second row onwards')
print(arr[1:,...])
print('\ne) Extract the third column onwards')
print(arr[...,2:])
print('\nf) obtain the square of array_hw')
print(arr**2)
print('\ng) Slice the element from the third row and fourth column position 3X4')
print(arr[2, 3])
print('\nf) obtain the total sum of array_hw')
print(arr.sum())
print('\nh) How many dimentions does array_hw have?')
print(arr.ndim)
print('\ni) What is the data type listed in array_hw?')
print(arr.dtype)
print('\nj) What is the size of the memory in bytes consumed by all the elements in array_hw?')
print(arr.nbytes)

a) Sort the flattened array
[1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]

b) Sort the second column
[5 7 7 9]

c) Sort the third row
[2 4 6 7 8 8]

d) Extract the second row onwards
[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

e) Extract the third column onwards
[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]

f) obtain the square of array_hw
[[25 25 64 64 81 64]
 [49 49 25  9 25 49]
 [64 49 64 16  4 36]
 [81 81 49  9  1 16]]

g) Slice the element from the third row and fourth column position 3X4
4

f) obtain the total sum of array_hw
145

h) How many dimentions does array_hw have?
2

i) What is the data type listed in array_hw?
int64

j) What is the size of the memory in bytes consumed by all the elements in array_hw?
192
